/*
 * Copyright (C) 2015-2018 CloudBeat Limited
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
// Dialogs

export const DIALOG = 'DIALOG';
export const DIALOG_FILE_CREATE = 'DIALOG_FILE_CREATE';
export const DIALOG_FILE_RENAME = 'DIALOG_FILE_RENAME';
export const DIALOG_FILE_SAVE = 'DIALOG_FILE_SAVE';
export const DIALOG_UPDATE = 'DIALOG_UPDATE';
export const DIALOG_SETTINGS = 'DIALOG_SETTINGS';
export const DIALOG_NEED_ISTALL_EXTENSION = 'DIALOG_NEED_ISTALL_EXTENSION';
export const DIALOG_OBJECT_ELEMENT_CREATE = 'DIALOG_OBJECT_ELEMENT_CREATE';
export const DIALOG_OBJECT_CONTAINER_CREATE = 'DIALOG_OBJECT_CONTAINER_CREATE';
export const DIALOG_OBJECT_ELEMENT_OR_CONTAINER_RENAME = 'DIALOG_OBJECT_ELEMENT_OR_CONTAINER_RENAME';
export const DIALOG_OBJECT_ELEMENT_OR_CONTAINER_REMOVE = 'DIALOG_OBJECT_ELEMENT_OR_CONTAINER_REMOVE';
export const DIALOG_INCORECT_CHROME_DRIVER_VERSION = 'DIALOG_INCORECT_CHROME_DRIVER_VERSION';
export const DIALOG_START_DOWNLOAD_CHROME_DRIVER = 'DIALOG_START_DOWNLOAD_CHROME_DRIVER';
export const DIALOG_SHOW_DOWNLOADING_CHROME_DRIVER_FAILED = 'DIALOG_SHOW_DOWNLOADING_CHROME_DRIVER_FAILED';
export const DIALOG_DOWNLOADING_CHROME_DRIVER = 'DIALOG_DOWNLOADING_CHROME_DRIVER';
export const DIALOG_DOWNLOADING_CHROME_DRIVER_SUCCESS = 'DIALOG_DOWNLOADING_CHROME_DRIVER_SUCCESS';
export const DIALOG_DOWNLOADING_CHROME_DRIVER_FAILED = 'DIALOG_DOWNLOADING_CHROME_DRIVER_FAILED';
