/*
 * Copyright (C) 2015-2018 CloudBeat Limited
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
export const TEST_START = 'TEST_START';
export const TEST_START_ALL = 'TEST_START_ALL';
export const TEST_STOP = 'TEST_STOP';
export const TEST_CONTINUE = 'TEST_CONTINUE';
export const TEST_SET_MAIN = 'TEST_SET_MAIN';
export const TEST_SET_TARGET = 'TEST_SET_TARGET';
export const TEST_SET_PROVIDER = 'TEST_SET_PROVIDER';
export const TEST_SET_MODE = 'TEST_SET_MODE';
export const TEST_SET_STEP_DELAY = 'TEST_SET_STEP_DELAY';
export const TEST_ADD_DEVICE = 'TEST_ADD_DEVICE';
export const TEST_REMOVE_DEVICE = 'TEST_REMOVE_DEVICE';
export const TEST_SET_SELENIUM_READY = 'TEST_SET_SELENIUM_READY';
export const TEST_SET_SELENIUM_PORT = 'TEST_SET_SELENIUM_PORT';
export const TEST_UPDATE_BREAKPOINTS = 'TEST_UPDATE_BREAKPOINTS';
export const WAIT_TEST_UPDATE_BREAKPOINTS = 'WAIT_TEST_UPDATE_BREAKPOINTS';
export const TEST_REMOVE_BREAKPOINTS = 'TEST_REMOVE_BREAKPOINTS';
export const TEST_UPDATE_RUN_SETTINGS = 'TEST_UPDATE_RUN_SETTINGS';
export const TEST_SELENIUM_PID = 'TEST_SELENIUM_PID';
export const TEST_EVENT_ENDED = 'TEST_EVENT_ENDED';
export const TEST_EVENT_BREAKPOINT = 'TEST_EVENT_BREAKPOINT';
export const TEST_EVENT_LINE_UPDATE = 'TEST_EVENT_LINE_UPDATE';
export const TEST_UPDATE_DISABLED_BREAKPOINTS = 'TEST_UPDATE_DISABLED_BREAKPOINTS';
export const TEST_UPDATE_RESOLVED_BREAKPOINT = 'TEST_UPDATE_RESOLVED_BREAKPOINT';
export const TEST_ERR_MAIN_SCRIPT_NOT_SAVED = 'MAIN_SCRIPT_NOT_SAVED';
export const TEST_ERR_MAIN_SCRIPT_NOT_SELECTED = 'TEST_ERR_MAIN_SCRIPT_NOT_SELECTED';
export const TEST_ERR_MAIN_SCRIPT_IS_EMPTY = 'TEST_ERR_MAIN_SCRIPT_IS_EMPTY';
export const TEST_MOVE_BREAKPOINTS_FROM_TMP_FILE_TO_REAL_FILE = 'TEST_MOVE_BREAKPOINTS_FROM_TMP_FILE_TO_REAL_FILE';


