#!/usr/bin/env node

var path = require('path');
var cp = require('child_process');

function printErr(str) {
    console.error('\033[31m' + str + '\033[0m');
}

if (process.platform !== 'win32' && process.arch === 'ia32') {
    console.error('Building on ia32 linux and darwin is not supported.');
    process.exit(1);
}

process.chdir(path.dirname(__dirname));

try {
    cp.execSync('npm install', 
                {
                    env: process.env,
                    stdio: ['inherit', 'inherit', 'inherit'],
                    maxBuffer: 10 * 1024 * 1024
                });
    cp.execSync('npm run build', 
                {
                    env: process.env,
                    stdio: ['inherit', 'inherit', 'inherit'],
                    maxBuffer: 10 * 1024 * 1024
                });
    cp.execSync('grunt ' + process.argv.slice(2).join(' '),
                {
                    env: process.env,
                    stdio: ['inherit', 'inherit', 'inherit'],
                    maxBuffer: 10 * 1024 * 1024
                });   
} catch (e) {
    printErr(e);
    return;
}
